name: Sync out of github

on: [push, delete, create]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to codeberg
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SYNC_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:RicardoRyn/plotfig.git
          destination-repo: git@codeberg.org:RicardoRyn/plotfig.git
      - name: Sync to gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SYNC_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:RicardoRyn/plotfig.git
          destination-repo: git@gitee.com:RicardoRyn/plotfig.git
